---
- name: Comment proxmox enterprise repository
  lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^'
    line: '#deb https://enterprise.proxmox.com/debian stretch pve-enterprise'

- name: Add hosts to /etc/hosts for ip resolve
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - resolve

- name: Create a cluster on master
  command: pvecm create my-cluster
  register: cluster_init
  when: inventory_hostname == groups['glusterfs_nodes'][0]
  failed_when: not "'cluster config '/etc/pve/corosync.conf' already exists' in cluster_init.stderr"

- name: Pause to create the cluster
  pause:
    seconds: 10

- name: Expected vote 1
  command: pvecm expected 1
  when: inventory_hostname == groups['glusterfs_nodes'][0]

- name: Nodes add themselves in cluster
  command: pvecm add {{ hostvars[groups['glusterfs_nodes'][0]]['ansible_default_ipv4']['address'] }} --force
  register: result
  until: result.rc == 0
  retries: 5
  when: inventory_hostname in groups['glusterfs_nodes'][1:]

- name: Create glusterfs storage
  template:
    src: storage.cfg.j2
    dest: /etc/pve/storage.cfg
  when: inventory_hostname == groups['glusterfs_nodes'][0]
  tags:
    - proxmox-storage

- name: Add no subscription repository
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve stretch pve-no-subscription"
    state: present

- name: Update repository packages
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

