---
- name: Set fact Proxmox master
  set_fact:
    proxmox_leader_node: "{{ groups[target+'_glusterfs_nodes'][0] }}"
  tags:
    - cluster

- name: Set fact for Proxmox agents
  set_fact:
    proxmox_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Add hosts to /etc/hosts for ip resolve
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - resolve

- name: Create a cluster on master
  command: pvecm create my-cluster
  register: cluster_init
  when: inventory_hostname == proxmox_leader_node
  failed_when: not "'cluster config '/etc/pve/corosync.conf' already exists' in cluster_init.stderr"

#- name: Expected vote 1
#  command: pvecm expected 1
#  when: inventory_hostname == proxmox_leader_node

- name: Nodes add themselves in cluster
  command: pvecm add {{ hostvars[proxmox_leader_node]['ansible_default_ipv4']['address'] }} --force
  register: result
  until: result.rc == 0
  retries: 5
  when: inventory_hostname in proxmox_nodes

