---
- name: Set fact for Glusterfs leader
  set_fact:
    gluster_leader: "{{ groups[target+'_glusterfs_nodes'][0] }}"

- name: Set fact for Glusterfs nodes
  set_fact:
    gluster_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Create volume group
  lvg:
    vg: "{{ glusterfs_vg_name }}"
    pvs: "/dev/{{ glusterfs_disk }}"


- name: Create logical volume for GlusterFS storage
  lvol:
    vg: "{{ glusterfs_vg_name }}"
    lv: "{{ glusterfs_storage }}"
    size: "{{ glusterfs_volume_size }}"

- name: Convert volume to thin-pool
  command: "lvconvert --force --type thin-pool -y {{ glusterfs_vg_name }}/{{ glusterfs_storage }}"
  register: lvconvert
  failed_when: not "'LV is already pool' in lvconvert.stderr"

- name: Create xfs filesystem on partition
  filesystem:
    fstype: xfs
    dev: "/dev/{{ glusterfs_vg_name }}/{{ glusterfs_storage }}"
    opts: -i size=512
  ignore_errors: yes
 

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line:  "/dev/{{ glusterfs_vg_name }}/{{ glusterfs_storage}} {{ storage_directory}}/{{ glusterfs_storage }} xfs defaults 0 0"

- name: Create the storage directory
  file:
    path: "{{ storage_directory }}/{{ glusterfs_storage }}"
    state: directory

- name: Mount the line added in fstab
  shell: mount -a

- name: Create brick's directory
  file:
    path: "{{ storage_directory}}/{{glusterfs_storage}}/brick"
    state: directory
