---
- name: Set fact for Glusterfs Primary node
  set_fact:
    gluster_leader: "{{ groups[target+'_glusterfs_nodes'][0] }}"

- name: Set fact for Glusterfs agents
  set_fact:
    gluster_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Comment proxmox enterprise repository
  lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^'
    line: '#deb https://enterprise.proxmox.com/debian stretch pve-enterprise'    

- name: Install GlusterFS server
  apt:
    name:
      - glusterfs-server
    state: present

- name: Create trusted storage pool(glusterfs cluster)
  command: gluster peer probe {{ hostvars[item]['inventory_hostname_short'] }}
  with_items: "{{ gluster_nodes }}"
  when: inventory_hostname == gluster_leader

- name: Create replicated volume
  command: gluster volume create {{ volume_name }} {{ volume_type }} {{ groups[target + '_glusterfs_nodes'] | count }} {{ (groups[target+'_glusterfs_nodes'] + [''])|join(':' + storage_directory + '/' + glusterfs_storage + '/brick ') }}
  register: create_cluster
  failed_when: create_cluster.rc !=0 and "already exists" not in create_cluster.stderr
  when: inventory_hostname == gluster_leader
