---
- name: Create xfs filesystem on partition
  filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ item.device }}"
  ignore_errors: yes
  with_items: "{{ filesystems }}"


- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line:  "{{ item.device}} {{ item.mountpoint }} {{ item.fs }} defaults 0 0"
  with_items: "{{ filesystems }}"

- name: Create the brick's directory
  file:
    path: "{{ item.mountpoint }}"
    state: directory
  with_items: "{{ filesystems }}"

- name: Mount the line added in fstab
  shell: mount -a


- name: Update repository packages
  apt:
    update_cache: yes

- name: Install GlusterFS server 
  apt:
    name:
      - glusterfs-server
    state: present

- name: Create volume
  gluster_volume: 
    state: present
    name: "{{ replication_volume.name }}"
    bricks: "{{ replication_volume.bricks | join (',') }}"
    replicas: "{{ groups[target + '_glusterfs_nodes'] | count }}"
    cluster: "{{ groups[target + '_glusterfs_nodes'] }}"
    options:
      auth.allow: "{{ groups[target+'_glusterfs_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
  when: inventory_hostname == "{{ groups[target+'_glusterfs_nodes'][0] }}"
