---
- name: Set fact for Glusterfs Primary node
  set_fact:
    gluster_leader: "{{ groups[target+'_glusterfs_nodes'][0] }}"

- name: Set fact for Glusterfs agents
  set_fact:
    gluster_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Update repository packages
  apt:
    update_cache: yes

- name: Install GlusterFS server and Zabbix agent
  apt:
    name:
      - glusterfs-server
    state: present

- name: Create volume
  gluster_volume: 
    state: present
    name: "{{ volume_name }}"
    bricks: "{{storage_directory}}/{{glusterfs_storage}}/brick"
    replicas: "{{ groups[target + '_glusterfs_nodes'] | count }}"
    cluster: "{{ groups[target + '_glusterfs_nodes'] }}"
    options:
      auth.allow: "{{ groups[target+'_glusterfs_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
  when: inventory_hostname == gluster_leader
