---
- name: Set fact for Glusterfs Primary node
  set_fact:
    gluster_leader: "{{ groups[target+'_glusterfs_nodes'][0] }}"

- name: Set fact for Glusterfs agents
  set_fact:
    gluster_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Comment proxmox enterprise repository
  lineinfile:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^'
    line: '#deb https://enterprise.proxmox.com/debian stretch pve-enterprise'
    state: present

- name: Install GlusterFS server
  apt:
    name:
      - glusterfs-server
    state: present


