---
- name: Download GPG key to apt 
  apt_key: 
    url: "{{ repo_key_url }}"
    state: present
  tags:
    - packages
    - gpg_key
    - apt-transport-https

- name: Add Glusterfs source repository
  apt_repository:
    repo: "{{ repo }}"
    state: present
    filename: gluster
  tags:
    - packages
    - source_repository

- name: Update repository packages
  apt:
    update_cache: yes
  tags:
    - packages

- name: Install GlusterFS server 
  apt:
    name:
      - glusterfs-server
      - git
    state: present
  tags:
    - packages
