---
- name: Set fact for Glusterfs leader
  set_fact:
    gluster_leader: "{{ groups[target+'_glusterfs_nodes'][0] }}"

- name: Set fact for Glusterfs nodes
  set_fact:
    gluster_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Create volume group
  lvg:
    vg: "{{ item }}"
    pvs: "{{lvm_volume_groups[item].physical_volumes }}"
  with_items: "{{ lvm_volume_groups }}"


- name: Create logical volume for GlusterFS storage
  lvol:
    vg: "{{ lvm_logical_volumes[item].vg }}"
    lv: "{{ item }}"
    size: "{{ lvm_logical_volumes[item].size }}"
  with_items: "{{ lvm_logical_volumes }}"

- name: Create xfs filesystem on partition
  filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ item.device }}"
  ignore_errors: yes
  with_items: "{{ filesystems }}"
 

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line:  "{{ item.device}} {{ item.mountpoint }} {{ item.fs }} defaults 0 0"
  with_items: "{{ filesystems }}"

- name: Create the brick's directory
  file:
    path: "{{ bricks_directory[item].path }}"
    state: directory
  with_items: "{{ bricks_directory }}"

- name: Mount the line added in fstab
  shell: mount -a

