---
- name: Set fact for Glusterfs leader
  set_fact:
    gluster_leader: "{{ groups[target+'_glusterfs_nodes'][0] }}"

- name: Set fact for Glusterfs nodes
  set_fact:
    gluster_nodes: "{{ groups[target+'_glusterfs_nodes'][1:] }}"

- name: Create volume group
  lvg:
    vg: "{{ lvm_volume_groups[item].name }}"
    pvs: "{{lvm_volume_groups[item].physical_volumes }}"
  with_items: "{{ lvm_volume_groups}}"


- name: Create logical volume for GlusterFS storage
  lvol:
    vg: "{{ lvm_logical_volumes[item].vg }}"
    lv: "{{ lvm_logical_volumes[item].name }}"
    size: "{{ lvm_logical_volumes[item].size }}"
  with_items: "{{ lvm_logical_volumes }}"

- name: Create xfs filesystem on partition
  filesystem:
    fstype: xfs
    dev: "/dev/{{ glusterfs_vg_name }}/{{ glusterfs_storage }}"
    opts: -i size=512
  ignore_errors: yes
 

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line:  "/dev/{{ glusterfs_vg_name }}/{{ glusterfs_storage}} {{ storage_directory}}/{{ glusterfs_storage }} xfs defaults 0 0"

- name: Create the storage directory
  file:
    path: "{{ storage_directory }}/{{ glusterfs_storage }}"
    state: directory

- name: Mount the line added in fstab
  shell: mount -a

- name: Create brick's directory
  file:
    path: "{{ storage_directory}}/{{glusterfs_storage}}/brick"
    state: directory
