---
- name: Install freeradius package
  apt:
    name:
      - freeradius
    state: present

- name: Install freeradius-ldap package
  apt:
    name:
      - freeradius-ldap
    state: present
  when: ldap_server is defined

- name: LDAP configuration file
  template:
    src: ldap.j2
    dest: /etc/freeradius/3.0/mods-available/ldap
    owner: freerad
    group: freerad
    mode: "0640"
  when: ldap_server is defined

- name: LDAP module link
  file:    
    src: ../mods-available/ldap
    dest: /etc/freeradius/3.0/mods-enabled/ldap
    owner: freerad
    group: freerad
    state: link
  when: ldap_server is defined

