---
- name: Install freeradius package
  apt:
    name:
      - freeradius
      - freeradius-ldap
    state: present

- name: Create LDAP module configuration file
  template:
    src: ldap.j2
    dest: /etc/freeradius/3.0/mods-available/ldap
    owner: freerad
    group: freerad
    mode: "0640"

- name: Copy EAP module configuration file
  copy:
    src: eap
    dest: /etc/freeradius/3.0/mods-available/eap
    owner: freerad
    group: freerad
    mode: "0640"

- name: Enable freeradius modules
  file:
    src: /etc/freeradius/3.0/mods-available/{{ item }}
    dest: /etc/freeradius/3.0/mods-enabled/{{ item }}
    owner: freerad
    group: freerad
    follow: no
    state: link
  with_items:
    - ldap
    - eap

- name: Copy site configurations
  copy:    
    src: "{{ item }}"
    dest: /etc/freeradius/3.0/sites-available/{{ item }}
    owner: freerad
    group: freerad
  with_items:
    - default
    - inner-tunnel

- name: Enable sites
  file:
    src: /etc/freeradius/3.0/sites-available/{{ item }}
    dest: /etc/freeradius/3.0/sites-enabled/{{ item }}
    follow: no
    owner: freerad
    group: freerad
    state: link
  with_items:
    - default
    - inner-tunnel

- name: Create Freeradius Clients configuration
  template:
    src: clients.conf.j2
    dest: /etc/freeradius/3.0/clients.conf
    owner: freerad
    group: freerad
    mode: "0640"

- name: Generate diffie hellman file
  openssl_dhparam:
    path: /etc/freeradius/3.0/certs/dh
    size: 2048

- name: Create Freeradius users file
  template:
    src: users.j2
    dest: /etc/freeradius/3.0/users
    owner: freerad
    group: freerad
    mode: "0640"

- name: Create Freeradius proxy configuration file
  template:
    src: proxy.conf.j2
    dest: /etc/freeradius/3.0/proxy.conf
    owner: freerad
    group: freerad
    mode: "0640"
  when: radius_servers is defined
