---
- name: Print Radius Incoming
  raw: /radius incoming print; quit
  register: output_incoming
  tags:
    - radius_incoming

- name: Print Radius Client
  raw: /radius print count-only where address="{{item.radius_server_address}}"; quit
  register: output_radius_client
  with_items: "{{mikrotik_radius_clients}}"
  tags:
    - radius

- name: Enable Change of Authorization with Radius
  raw: /radius incoming set accept={{item.radius_incoming}} port={{item.radius_incoming_port}}; quit
  when: "'yes' not in output_incoming.stdout and item.radius_incoming is defined"
  with_items: "{{mikrotik_radius_clients}}"
  tags:
    - radius_incoming

- name: Add Radius Client
  raw: /radius add service={{item.radius_services}} address={{item.radius_server_address}} secret={{item.radius_server_shared_secret}}; quit
  when: item.radius_server_address == "0"
  with_items: "{{mikrotik_radius_clients}}"
  tags: radius

- name: Users use radius
  raw: /user aaa set use-radius={{item.use_radius}}; quit
  with_items: "{{mikrotik_radius_clients}}"
  when: item.use_radius is defined
  tags: radius


