---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install zabbix package
  apt:
    name:
      - zabbix-agent
    state: latest

