---
- include_vars: creds.yml
- name: Add ip address in zabbix configuration file
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: 'Server={{zabbix_server}}'

- name: Add agent in zabbix server
  local_action:
    module: zabbix_host
    server_url: "{{zabbix_url}}"
    login_user: "{{zabbix_username}}"
    host_groups:
      - Linux servers
    login_password: "{{zabbix_password}}"
    host_name: "{{ansible_hostname}}"
    visible_name: "{{ansible_hostname}}"
    link_templates:
      - Template OS Linux
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ansible_default_ipv6['address']}}"
        dns: ""
        port: 10050

- name: Restart zabbix-agent
  command: service zabbix-agent restart
