---
- name: Create volume groups
  lvg:
    vg: "{{ item }}"
    pvs: "{{lvm_volume_groups[item].physical_volumes }}"
  with_items: "{{ lvm_volume_groups }}"


- name: Create logical volumes 
  lvol:
    vg: "{{ lvm_logical_volumes[item].vg }}"
    lv: "{{ item }}"
    size: "{{ lvm_logical_volumes[item].size }}"
  with_items: "{{ lvm_logical_volumes }}"
