---
- name: Create volume groups
  lvg:
    vg: "{{ item }}"
    pvs: "{{lvm_volume_groups[item].physical_volumes }}"
  with_items: "{{ lvm_volume_groups }}"
  tags:
    - volume_groups

- name: Create thin-pools
  lvol:
    vg: "{{ lvm_thin_pools[item].vg }}"
    lv: "{{ item }}"
    size: "{{ lvm_thin_pools[item].size }}"
    opts: -T
  with_items: "{{ lvm_thin_pools }}"
  when: lvm_thin_pools is defined

- name: Create Thin Volumes
  lvol:
    vg: "{{ lvm_thin_volumes[item].vg }}"
    lv: "{{ item }}"
    size: "{{ lvm_thin_volumes[item].size }}"
    opts: -V -T {{ lvm_thin_volumes[item].vg }}/{{ lvm_thin_volumes[item].thin_pool }}
  with_items: "{{ lvm_thin_volumes }}"
  when: lvm_thin_volumes is defined


- name: Create logical volumes 
  lvol:
    vg: "{{ lvm_logical_volumes[item].vg }}"
    lv: "{{ item }}"
    opts: -V{{ lvm_logical_volumes[item].size }} -T {{ lvm_logical_volumes[item].vg }}/
  with_items: "{{ lvm_logical_volumes }}"
  when: lvm_logical_volumes is defined
