---
- name: Install lvm2 and thin-provisioning-tools packages
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - lvm2
    - thin-provisioning-tools
  tags:
    - packages                   
